USE [master]
GO

IF EXISTS (SELECT name FROM master.sys.databases WHERE name = 'DB_GER_VEICULO')
DROP DATABASE DB_GER_VEICULO;
GO

-------------------------------------
CREATE DATABASE DB_GER_VEICULO
USE DB_GER_VEICULO
--------------------------------------

CREATE TABLE TBL_LOGINS (
LOG_INT_ID INT NOT NULL IDENTITY(1,1),
LOG_STR_LOGIN VARCHAR(20) NOT NULL,
LOG_STR_SENHA VARCHAR(20) NOT NULL,
)

ALTER TABLE TBL_LOGINS 
ADD CONSTRAINT PK_LOGINS_ID
PRIMARY KEY (LOG_INT_ID);

---------------------------------------------------------------------------------

CREATE TABLE TBL_FUNCIONARIO
(
  FUN_INT_ID INT NOT NULL IDENTITY (1,1),
  LOG_INT_ID INT NOT NULL,
  FUN_STR_NOME VARCHAR(60) NOT NULL,
  FUN_DATE_NASC DATETIME NOT NULL,
  FUN_STR_CPF VARCHAR (11) NOT NULL UNIQUE,
  FUN_STR_CNH VARCHAR(8) UNIQUE,
  FUN_STR_RG VARCHAR (9) NOT NULL UNIQUE,
  FUN_STR_CARGO VARCHAR (30) NOT NULL,
  FUN_STR_SEXO CHAR(1) NOT NULL,
  FUN_STR_EMAIL VARCHAR(60),
)
---PRIMARY KEY
ALTER TABLE TBL_FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY (FUN_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_FUNCIONARIO
ADD CONSTRAINT FK_LOGINS_ID FOREIGN KEY (LOG_INT_ID) REFERENCES TBL_LOGINS

--------------------------------------------------------------------------------

CREATE TABLE TBL_TELEFONE
(
  TEL_INT_ID INT NOT NULL IDENTITY(1,1),
  FUN_INT_ID INT NOT NULL,
  TEL_INT_DDD INT,
  TEL_INT_CELULAR INT,
  TEL_INT_FIXO INT NOT NULL,
  TEL_STR_OPERADORA VARCHAR(15),
)

---PRIMARY KEY
ALTER TABLE TBL_TELEFONE
ADD CONSTRAINT PK_TELEFONE_ID PRIMARY KEY (TEL_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_TELEFONE
ADD CONSTRAINT FK_FUNCIONARIO_ID FOREIGN KEY (FUN_INT_ID) REFERENCES TBL_FUNCIONARIO

-----------------------------------------------------------------------------------
CREATE TABLE TBL_ESTADO
(
-- EST_INT_ID INT NOT NULL IDENTITY(1,1),
 EST_INT_CODUF INT NOT NULL,
 EST_STR_NOME VARCHAR(30) NOT NULL,
 EST_STR_UF CHAR(2) NOT NULL,
 EST_INT_IBGE INT NOT NULL,
)

---PRIMARY KEY
ALTER TABLE TBL_ESTADO
ADD CONSTRAINT PK_ESTADOUF_ID PRIMARY KEY (EST_INT_CODUF)

-----------------------------------------------------------------------------------------

CREATE TABLE TBL_CIDADE
(
  CID_INT_ID int NOT NULL,
  CID_STR_NOME varchar(120) NOT NULL,
  EST_INT_CODUF int NOT NULL,
  CID_INT_IBGE int NOT NULL
)
---PRIMARY KEY
ALTER TABLE TBL_CIDADE
ADD CONSTRAINT PK_CIDADE_ID PRIMARY KEY (CID_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_CIDADE
ADD CONSTRAINT FK_ESTADOUF_ID FOREIGN KEY (EST_INT_CODUF) REFERENCES TBL_ESTADO 

----------------------------------------------------------------------------------------

CREATE TABLE TBL_ENDERECO
(
 END_INT_ID INT NOT NULL IDENTITY(1,1),
 CID_INT_ID INT NOT NULL,
 EST_INT_CODUF INT NOT NULL,
 END_STR_RUA VARCHAR(60) NOT NULL,
 END_INT_NUMERO INT NOT NULL,
 END_STR_BAIRRO VARCHAR (60),
 END_INT_CEP INT NOT NULL,
 END_STR_COMPLEMENTO VARCHAR(60)
)
---PRIMARY KEY
ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (END_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT FK_CIDADE_ID FOREIGN KEY (CID_INT_ID) REFERENCES TBL_CIDADE 

ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT FK_ESTADO_ID FOREIGN KEY (EST_INT_CODUF) REFERENCES TBL_ESTADO 


-----------------------------------------------------------------------------------
--REMOVENDO DUPLICIDADE TESTE------------------------------------------------------


CREATE TABLE TBL_ENDERECO_FUNCIONARIO
(
 END_INT_ID INT NOT NULL,
 FUN_INT_ID INT NOT NULL,
)
ALTER TABLE TBL_ENDERECO_FUNCIONARIO
ADD CONSTRAINT FK_FUN_EST_ID FOREIGN KEY (FUN_INT_ID) REFERENCES TBL_FUNCIONARIO

ALTER TABLE TBL_ENDERECO_FUNCIONARIO
ADD CONSTRAINT FK_END_FUN_EST_ID FOREIGN KEY (END_INT_ID) REFERENCES TBL_ENDERECO

-------------------------------------------------------------------------------------

CREATE TABLE TBL_FOTO
(
FOT_INT_ID INT NOT NULL IDENTITY(1,1),
FUN_INT_ID INT,
FOTO VARBINARY(MAX)
)

ALTER TABLE TBL_FOTO
ADD CONSTRAINT PK_FOTO_ID PRIMARY KEY (FOT_INT_ID)

ALTER TABLE TBL_FOTO
ADD CONSTRAINT FK_FUN_FOTO_ID FOREIGN KEY (FUN_INT_ID) REFERENCES TBL_FUNCIONARIO