USE DB_GER_VEICULO

--
-- Inserindo dados na tabela "estado"
--

INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE) VALUES(1, 'Acre', 'AC', 12)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(2, 'Alagoas', 'AL', 27)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(3, 'Amazonas', 'AM', 13)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(4, 'Amapá', 'AP', 16)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(5, 'Bahia', 'BA', 29)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(6, 'Ceará', 'CE', 23)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(7, 'Distrito Federal', 'DF', 53)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(8, 'Espírito Santo', 'ES', 32)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(9, 'Goiás', 'GO', 52)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(10, 'Maranhão', 'MA', 21)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(11, 'Minas Gerais', 'MG', 31)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(12, 'Mato Grosso do Sul', 'MS', 50)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(13, 'Mato Grosso', 'MT', 51)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(14, 'Pará', 'PA', 15)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(15, 'Paraíba', 'PB', 25)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(16, 'Pernambuco', 'PE', 26)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(17, 'Piauí', 'PI', 22)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(18, 'Paraná', 'PR', 41)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(19, 'Rio de Janeiro', 'RJ', 33)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(20, 'Rio Grande do Norte', 'RN', 24)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(21, 'Rondônia', 'RO', 11)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(22, 'Roraima', 'RR', 14)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(23, 'Rio Grande do Sul', 'RS', 43)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(24, 'Santa Catarina', 'SC', 42)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(25, 'Sergipe', 'SE', 28)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(26, 'São Paulo', 'SP', 35)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(27, 'Tocantins', 'TO', 17)
INSERT INTO TBL_ESTADO (EST_INT_CODUF, EST_STR_NOME , EST_STR_UF, EST_INT_IBGE)  VALUES(99, 'Exterior', 'EX', 99);

SELECT *FROM TBL_ESTADO