USE DB_GER_VEICULO

SELECT * FROM TBL_LOGINS
SELECT * FROM TBL_FUNCIONARIO
SELECT * FROM TBL_TELEFONE
SELECT * FROM TBL_ENDERECO
SELECT * FROM TBL_FOTO
SELECT * FROM TBL_ENDERECO_FUNCIONARIO

SELECT * FROM TBL_EMPRESA
SELECT * FROM TBL_MOTORISTA
SELECT * FROM TBL_CNH 



DELETE TBL_ENDERECO_FUNCIONARIO WHERE FUN_INT_ID = 9
DELETE TBL_ENDERECO WHERE END_INT_ID = 7
DELETE TBL_FUNCIONARIO WHERE FUN_INT_ID = 7
DELETE TBL_FOTO WHERE FOT_INT_ID = 7
DELETE TBL_TELEFONE WHERE TEL_INT_ID = 7
DELETE TBL_LOGINS WHERE LOG_INT_ID = 7



--select DO CONSULTAR USUARIO
SELECT F.FUN_STR_NOME, CONVERT(VARCHAR(10),F.FUN_DATE_NASC,103) AS NASC, F.FUN_STR_CPF, F.FUN_STR_RG, F.FUN_STR_CARGO, F.FUN_STR_SEXO, F.FUN_STR_EMAIL, T.TEL_INT_DDD, T.TEL_INT_CELULAR, 
T.TEL_INT_FIXO, T.TEL_STR_OPERADORA, E.END_STR_RUA, E.END_INT_NUMERO, E.END_STR_COMPLEMENTO, E.END_STR_BAIRRO, E.END_INT_CEP, ES.EST_STR_NOME, C.CID_STR_NOME, 
FT.FOTO FROM TBL_FUNCIONARIO AS F
INNER JOIN TBL_TELEFONE AS T ON T.TEL_INT_ID = F.TEL_INT_ID 
INNER JOIN TBL_ENDERECO_FUNCIONARIO AS EF ON EF.FUN_INT_ID = F.FUN_INT_ID
INNER JOIN TBL_ENDERECO AS E ON E.END_INT_ID = EF.END_INT_ID
INNER JOIN TBL_ESTADO AS ES ON ES.EST_INT_CODUF = E.EST_INT_CODUF
INNER JOIN TBL_CIDADE AS C ON C.CID_INT_ID = E.CID_INT_ID
INNER JOIN TBL_FOTO AS FT ON FT.FOT_INT_ID = F.FOT_INT_ID
WHERE F.FUN_INT_ID = 4

--select DO CONSULTAR EMPRESA
SELECT EP.EMP_INT_ID, EP.EMP_STR_NOME,EP.EMP_STR_CNPJ,EP.EMP_STR_DESC,EP.EMP_STR_EMAIL,EP.EMP_STR_STATUS,
T.TEL_INT_CELULAR,T.TEL_STR_OPERADORA,T.TEL_INT_DDD, T.TEL_INT_FIXO,E.END_STR_RUA,E.END_INT_NUMERO,E.END_STR_BAIRRO, 
E.END_STR_COMPLEMENTO,E.END_INT_CEP, ES.EST_STR_NOME, C.CID_STR_NOME FROM TBL_EMPRESA AS EP
INNER JOIN TBL_TELEFONE AS T ON EP.TEL_INT_ID = T.TEL_INT_ID 
INNER JOIN TBL_ENDERECO_EMPRESA AS EE ON EE.EMP_INT_ID = EP.EMP_INT_ID
INNER JOIN TBL_ENDERECO AS E ON E.END_INT_ID = EE.END_INT_ID
INNER JOIN TBL_ESTADO AS ES ON ES.EST_INT_CODUF = E.EST_INT_CODUF
INNER JOIN TBL_CIDADE AS C ON C.CID_INT_ID = E.CID_INT_ID
WHERE  EP.EMP_INT_ID = 1

--select DO CONSULTAR MOTORISTA
SELECT M.MOT_INT_ID, M.MOT_STR_NOME,CONVERT(VARCHAR(10),M.MOT_DATE_NASC,103),M.MOT_STR_CPF,M.MOT_STR_RG,M.MOT_STR_SEXO,M.MOT_STR_EMAIL,C.CNH_STR_REGISTRO,CONVERT(VARCHAR(10),c.CNH_DATE_VALIDADE,103),C.CNH_STR_CATEGORIA, 
T.TEL_INT_CELULAR,T.TEL_STR_OPERADORA,T.TEL_INT_FIXO,T.TEL_INT_DDD, EP.EMP_STR_NOME AS EMPRESA, ED.END_STR_RUA, ED.END_INT_NUMERO,ED.END_STR_COMPLEMENTO,
ED.END_STR_BAIRRO, ED.END_INT_CEP, ES.EST_STR_NOME, CD.CID_STR_NOME, FT.FOTO FROM TBL_MOTORISTA AS M
INNER JOIN TBL_CNH AS C ON C.CNH_INT_ID = M.CNH_INT_ID
INNER JOIN TBL_TELEFONE AS T ON T.TEL_INT_ID = M.MOT_INT_ID
INNER JOIN TBL_EMPRESA AS EP ON EP.EMP_INT_ID = M.EMP_INT_ID
INNER JOIN TBL_ENDERECO_MOTORISTA AS EM ON EM.MOT_INT_ID = M.MOT_INT_ID
INNER JOIN TBL_ENDERECO AS ED ON ED.END_INT_ID = EM.END_INT_ID
INNER JOIN TBL_ESTADO AS ES ON ES.EST_INT_CODUF = ED.EST_INT_CODUF
INNER JOIN TBL_CIDADE AS CD ON CD.CID_INT_ID = ED.CID_INT_ID
INNER JOIN TBL_FOTO AS FT ON FT.FOT_INT_ID = M.FOT_INT_ID
WHERE M.MOT_INT_ID = 2

--TRAZ TODOS OS ID DO MOTORISTA
SELECT T.TEL_INT_ID, EM.MOT_INT_ID, E.END_INT_ID, FT.FOT_INT_ID, CH.CNH_INT_ID,EP.EMP_INT_ID FROM TBL_MOTORISTA AS M 
INNER JOIN TBL_TELEFONE AS T ON T.TEL_INT_ID = M.TEL_INT_ID 
INNER JOIN TBL_ENDERECO_MOTORISTA AS EM ON M.MOT_INT_ID = EM.MOT_INT_ID
INNER JOIN TBL_ENDERECO AS E ON EM.END_INT_ID = E.END_INT_ID
INNER JOIN TBL_FOTO AS FT ON FT.FOT_INT_ID = M.FOT_INT_ID
INNER JOIN TBL_CNH AS CH ON CH.CNH_INT_ID = M.CNH_INT_ID
INNER JOIN TBL_EMPRESA AS EP ON EP.EMP_INT_ID = M.EMP_INT_ID
WHERE M.MOT_INT_ID = 1

--TRAZ TODOS OS ID DO FUNCIONARIO
SELECT F.FUN_INT_ID, T.TEL_INT_ID, E.END_INT_ID, FT.FOT_INT_ID, L.LOG_INT_ID  FROM TBL_FUNCIONARIO AS F 
INNER JOIN TBL_ENDERECO_FUNCIONARIO AS EF ON EF.FUN_INT_ID = F.FUN_INT_ID
INNER JOIN TBL_ENDERECO AS E ON E.END_INT_ID = EF.END_INT_ID
INNER JOIN TBL_TELEFONE AS T ON T.TEL_INT_ID = F.TEL_INT_ID
INNER JOIN TBL_FOTO AS FT ON FT.FOT_INT_ID = F.FOT_INT_ID
INNER JOIN TBL_LOGINS AS L ON L.LOG_INT_ID = F.LOG_INT_ID
WHERE F.FUN_INT_ID = 1






UPDATE TBL_FUNCIONARIO SET LOG_INT_ID = 6, TEL_INT_ID = 6, FOT_INT_ID = 6 WHERE FUN_INT_ID = 6

-- update Usuario
UPDATE TBL_FUNCIONARIO
SET FUN_STR_NOME = '', FUN_DATE_NASC = '', FUN_STR_CPF = '' , FUN_STR_RG = '',FUN_STR_CNH = '', FUN_STR_CARGO = '', FUN_STR_SEXO = '' , FUN_STR_EMAIL='' WHERE FUN_INT_ID = 1


-- update Motorista
UPDATE TBL_MOTORISTA SET MOT_STR_NOME = '', MOT_DATE_NASC = '', MOT_STR_CPF = '' , MOT_STR_RG = '', MOT_STR_SEXO = '' , MOT_STR_EMAIL='' WHERE MOT_INT_ID = 1

-- update TELEFONE

UPDATE TBL_TELEFONE
SET TEL_INT_DDD = 030 , TEL_INT_FIXO = 81395412, TEL_INT_CELULAR = 555555588 ,TEL_STR_OPERADORA= 'Nextel' WHERE TEL_INT_ID = 5

-- update ENDERECO
UPDATE TBL_ENDERECO SET END_STR_RUA ='Madalena' , END_INT_NUMERO= 30, END_STR_COMPLEMENTO='Travessa Z' , END_STR_BAIRRO='Agua Preta' , END_INT_CEP= 05037020 , EST_INT_CODUF= 26 , CID_INT_ID= 5270 WHERE END_INT_ID = 2

-- update CNH
UPDATE TBL_CNH SET CNH_STR_REGISTRO = '', CNH_DATE_VALIDADE = '', CNH_STR_CATEGORIA = '' WHERE CNH_INT_ID = 


-- update EMPRESA
UPDATE TBL_EMPRESA SET EMP_STR_NOME = '', EMP_STR_CNPJ ='',EMP_STR_DESC = '',EMP_STR_EMAIL = '',EMP_STR_STATUS ='' WHERE EMP_INT_ID = 


sp_helpconstraint 'TBL_foto','nomsg'



