-- DELETA TUDO QUE TEM ALVER COM FUNCIONARIO
BEGIN TRANSACTION
DELETE TBL_ENDERECO WHERE END_INT_ID =2
DELETE TBL_CIDADE  WHERE CID_INT_ID=2
DELETE TBL_ESTADO WHERE EST_INT_ID=2
DELETE TBL_ESTADO_FUNCIONARIO WHERE EST_INT_ID =2
DELETE TBL_TELEFONE WHERE TEL_INT_ID =2 
DELETE TBL_FUNCIONARIO WHERE FUN_INT_ID =2 
DELETE TBL_LOGINS WHERE LOG_INT_ID =2
COMMIT

-- insert varias tabelas.
BEGIN TRANSACTION
INSERT INTO TBL_LOGINS(LOG_STR_LOGIN,LOG_STR_SENHA) VALUES ('gabs123','gabys123');





SELECT F.FUN_INT_ID AS Id, F.FUN_STR_NOME AS Nome, F.FUN_STR_RG AS RG, T.TEL_INT_CELULAR AS Celular 
FROM TBL_FUNCIONARIO AS F INNER JOIN TBL_TELEFONE AS T ON T.FUN_INT_ID = F.FUN_INT_ID;