USE [master]
GO

IF EXISTS (SELECT name FROM master.sys.databases WHERE name = 'DB_GER_VEICULO')
DROP DATABASE DB_GER_VEICULO;
GO

-------------------------------------
CREATE DATABASE DB_GER_VEICULO
USE DB_GER_VEICULO
--------------------------------------

CREATE TABLE TBL_LOGINS (
LOG_INT_ID INT NOT NULL IDENTITY(1,1),
LOG_STR_LOGIN VARCHAR(20) NOT NULL,
LOG_STR_SENHA VARCHAR(20) NOT NULL,
)

ALTER TABLE TBL_LOGINS 
ADD CONSTRAINT PK_LOGINS_ID
PRIMARY KEY (LOG_INT_ID);

INSERT INTO TBL_LOGINS(LOG_STR_LOGIN, LOG_STR_SENHA) VALUES ('admin123','admin123')
INSERT INTO TBL_LOGINS (LOG_STR_LOGIN,LOG_STR_SENHA) VALUES ('lucas123','lucas123')
INSERT INTO TBL_LOGINS (LOG_STR_LOGIN,LOG_STR_SENHA) VALUES ('joao123','joao123')


-------------------------------------------------------------------------------------

CREATE TABLE TBL_FUNCIONARIO
(
  FUN_INT_ID INT NOT NULL IDENTITY (1,1),
  LOG_INT_ID INT NOT NULL,
  FUN_STR_NOME VARCHAR(60) NOT NULL,
  FUN_DATE_NASC DATETIME NOT NULL,
  FUN_STR_CPF VARCHAR (11) NOT NULL UNIQUE,
  FUN_STR_CNH VARCHAR(8) UNIQUE,
  FUN_STR_RG VARCHAR (9) NOT NULL UNIQUE,
  FUN_STR_CARGO VARCHAR (30) NOT NULL,
  FUN_STR_SEXO CHAR(1) NOT NULL,
  FUN_STR_EMAIL VARCHAR(60),
)
---PRIMARY KEY
ALTER TABLE TBL_FUNCIONARIO
ADD CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY (FUN_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_FUNCIONARIO
ADD CONSTRAINT FK_LOGINS_ID FOREIGN KEY (LOG_INT_ID) REFERENCES TBL_LOGINS

---INSERT VALORES
INSERT INTO TBL_FUNCIONARIO(FUN_STR_NOME,FUN_DATE_NASC,FUN_STR_CPF,FUN_STR_CNH,FUN_STR_RG,FUN_STR_CARGO,FUN_STR_SEXO,FUN_STR_EMAIL,LOG_INT_ID)
VALUES ('Lucas Alves de Abreu','19950321',42600603230,87596485,415431691,'administrador','m','lucas_alves_abreu@hotmail.com',1)

INSERT INTO TBL_FUNCIONARIO (FUN_STR_NOME,FUN_DATE_NASC,FUN_STR_CPF,FUN_STR_CNH,FUN_STR_RG,FUN_STR_CARGO,FUN_STR_SEXO,FUN_STR_EMAIL,LOG_INT_ID)
VALUES('Marcos Alverto','19950508','36574893541','21478569','145875635','Administrador','m','alvero@hotmail.com',2)

INSERT INTO TBL_FUNCIONARIO (FUN_STR_NOME,FUN_DATE_NASC,FUN_STR_CPF,FUN_STR_CNH,FUN_STR_RG,FUN_STR_CARGO,FUN_STR_SEXO,FUN_STR_EMAIL,LOG_INT_ID)
VALUES('João Varotti','19960228','02574893546','00478567','125875630','Administrador','m','joaova.rotti@hotmail.com',3)  


-----------------------------------------------------------------

CREATE TABLE TBL_TELEFONE
(
  TEL_INT_ID INT NOT NULL IDENTITY(1,1),
  FUN_INT_ID INT NOT NULL,
  TEL_INT_DDD INT,
  TEL_INT_CELULAR INT,
  TEL_INT_FIXO INT NOT NULL,
  TEL_STR_OPERADORA VARCHAR(15),
)

---PRIMARY KEY
ALTER TABLE TBL_TELEFONE
ADD CONSTRAINT PK_TELEFONE_ID PRIMARY KEY (TEL_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_TELEFONE
ADD CONSTRAINT FK_FUNCIONARIO_ID FOREIGN KEY (FUN_INT_ID) REFERENCES TBL_FUNCIONARIO

INSERT INTO TBL_TELEFONE(TEL_INT_DDD,TEL_INT_CELULAR,TEL_INT_FIXO,TEL_STR_OPERADORA,FUN_INT_ID) 
VALUES (011,989760596,36173934,'TIM',1)

INSERT INTO TBL_TELEFONE(TEL_INT_DDD,TEL_INT_CELULAR,TEL_INT_FIXO,TEL_STR_OPERADORA,FUN_INT_ID) 
VALUES (011,659760597,11173934,'Claro',2)

INSERT INTO TBL_TELEFONE(TEL_INT_DDD,TEL_INT_CELULAR,TEL_INT_FIXO,TEL_STR_OPERADORA,FUN_INT_ID) 
VALUES (012,859760593,55173934,'Vivo',3)

-----------------------------------------------------------------------------------
CREATE TABLE TBL_ESTADO
(
 EST_INT_ID INT NOT NULL IDENTITY(1,1),
 EST_STR_NOME VARCHAR(30) NOT NULL
)
---PRIMARY KEY
ALTER TABLE TBL_ESTADO
ADD CONSTRAINT PK_ESTADO_ID PRIMARY KEY (EST_INT_ID)

INSERT INTO TBL_ESTADO (EST_STR_NOME) VALUES('São Paulo')
INSERT INTO TBL_ESTADO (EST_STR_NOME) VALUES('São Paulo')
INSERT INTO TBL_ESTADO (EST_STR_NOME) VALUES('Minas gerais')


-----------------------------------------------------------------------------------
--REMOVENDO DUPLICIDADE TESTE-------------------------------------------------------
CREATE TABLE TBL_ESTADO_FUNCIONARIO
(
 EST_INT_ID INT NOT NULL,
 FUN_INT_ID INT NOT NULL,
)
ALTER TABLE TBL_ESTADO_FUNCIONARIO
ADD CONSTRAINT FK_FUN_EST_ID FOREIGN KEY (FUN_INT_ID) REFERENCES TBL_FUNCIONARIO

ALTER TABLE TBL_ESTADO_FUNCIONARIO
ADD CONSTRAINT FK_EST_FUN_EST_ID FOREIGN KEY (EST_INT_ID) REFERENCES TBL_FUNCIONARIO

INSERT INTO TBL_ESTADO_FUNCIONARIO(EST_INT_ID,FUN_INT_ID) VALUES (1,1)
INSERT INTO TBL_ESTADO_FUNCIONARIO(EST_INT_ID,FUN_INT_ID) VALUES (2,2)
INSERT INTO TBL_ESTADO_FUNCIONARIO(EST_INT_ID,FUN_INT_ID) VALUES (3,3)

-----------------------------------------------------------------------------------------
CREATE TABLE TBL_CIDADE
(
 CID_INT_ID INT NOT NULL IDENTITY(1,1),
 EST_INT_ID INT NOT NULL,
 CID_STR_NOME VARCHAR(30) NOT NULL
)
---PRIMARY KEY
ALTER TABLE TBL_CIDADE
ADD CONSTRAINT PK_CIDADE_ID PRIMARY KEY (CID_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_CIDADE
ADD CONSTRAINT FK_ESTADO_ID FOREIGN KEY (EST_INT_ID) REFERENCES TBL_ESTADO 

INSERT INTO TBL_CIDADE (CID_STR_NOME,EST_INT_ID) VALUES('São Paulo',1)
INSERT INTO TBL_CIDADE (CID_STR_NOME,EST_INT_ID) VALUES('Barueri',2)
INSERT INTO TBL_CIDADE (CID_STR_NOME,EST_INT_ID) VALUES('Alagoa',3)

-------------------------------------------------------------------------------------------

CREATE TABLE TBL_ENDERECO
(
 END_INT_ID INT NOT NULL IDENTITY(1,1),
 CID_INT_ID INT NOT NULL,
 END_STR_RUA VARCHAR(60) NOT NULL,
 END_INT_NUMERO INT NOT NULL,
 END_STR_BAIRRO VARCHAR (60),
 END_INT_CEP INT NOT NULL,
 END_STR_COMPLEMENTO VARCHAR(60)
)
---PRIMARY KEY
ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (END_INT_ID)
---FOREIGN KEY
ALTER TABLE TBL_ENDERECO
ADD CONSTRAINT FK_CIDADE_ID FOREIGN KEY (CID_INT_ID) REFERENCES TBL_CIDADE 

INSERT INTO TBL_ENDERECO (END_STR_RUA,END_INT_NUMERO,END_STR_BAIRRO,END_INT_CEP,END_STR_COMPLEMENTO,CID_INT_ID) 
VALUES('Cap Francisco T nogueira', 14,'Água Branca',05037030,'Travessa I',1)

INSERT INTO TBL_ENDERECO (END_STR_RUA,END_INT_NUMERO,END_STR_BAIRRO,END_INT_CEP,END_STR_COMPLEMENTO,CID_INT_ID) 
VALUES('Av Moca natal', 103,'Moca',03037012,'Travessa E',2)

INSERT INTO TBL_ENDERECO (END_STR_RUA,END_INT_NUMERO,END_STR_BAIRRO,END_INT_CEP,END_STR_COMPLEMENTO,CID_INT_ID) 
VALUES('Avenida Angélica', 12,'Centro minas',15037018,'Cruzamento com alagoas',3)

-----------------------------------------------------------------------------------------------------------------

